DROP TABLE IF EXISTS meal_plans CASCADE;
DROP TABLE IF EXISTS plan_recipes CASCADE;
DROP TABLE IF EXISTS recipe_tags CASCADE;
DROP TABLE IF EXISTS tags CASCADE;

CREATE TABLE meal_plans (
  id SERIAL PRIMARY KEY NOT NULL, 
  name VARCHAR(100) NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  plan_array JSON NOT NULL
);

