DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS meal_plans CASCADE;
DROP TABLE IF EXISTS user_recipes CASCADE;
DROP TABLE IF EXISTS recipes CASCADE;
DROP TABLE IF EXISTS recipe_tags CASCADE;
DROP TABLE IF EXISTS tags CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE meal_plans (
  id SERIAL PRIMARY KEY NOT NULL, 
  name VARCHAR(100) NOT NULL,
  recipe_id INTEGER[21] REFERENCES recipes(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE user_recipes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
  recipe_id INTEGER[21] REFERENCES recipes(id) ON DELETE CASCADE,
  saved_date DATE NOT NULL,
  rating INTEGER
);

CREATE TABLE recipes (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  image_url VARCHAR(255), 
  summary TEXT,
  ingredients VARCHAR(150)[] NOT NULL,
  preperation TEXT NOT NULL,
  author VARCHAR(100),
  source_url VARCHAR(255),
  prep_time INTEGER,
  servings INTEGER
);

CREATE TABLE recipe_tags (
  id SERIAL PRIMARY KEY NOT NULL,
  tag_id REFERENCES tags(id) ON DELETE CASCADE,
  recipe_id REFERENCES recipes(id) ON DELETE CASCADE
);

CREATE TABLE tags (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(100) NOT NULL,
);